name: Test App
on: [push]
jobs:
  test-app:
    name: Run Application Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
          python-version: "3.10"
    - name: Test with 10 numbers
      run: python find_lowest_number.py test_data/test1_input.txt test_data/test1_expected.txt
    - name: Test the lowest number
      run: diff test_data/test1_expected.txt test_data/test1_input.txt

    - name: Test with 1 number
      run: python find_lowest_number.py test_data/test2_input.txt test_data/test2_expected.txt
    - name: Test if number matched
      run: diff test_data/test2_expected.txt test_data/test2_input.txt

    - name: Test with blank file
      run: python find_lowest_number.py test_data/test3_input.txt test_data/test3_expected.txt
    - name: Test if blank
      run: diff test_data/test3_expected.txt test_data/test3_input.txt
