name: Test App
on: [push]
jobs:
  test-app:
    name: Run Application Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test with 10 numbers
      run: python find_lowest_number.py test_data/test1_input.txt output1.txt
        diff output1.txt test_data/test1_expected.txt

    - name: Test with 1 number
      run: python find_lowest_number.py test_data/test2_input.txt output2.txt
        diff output2.txt test_data/test2_expected.txt

    - name: Test with blank file
      run: python find_lowest_number.py test_data/test3_input.txt output3.txt
        diff output3.txt test_data/test3_expected.txt
