name: Test App
on: [push]
jobs:
  test-app:
    name: Run Application Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test with 10 numbers
      run: python find_lowest_number.py test1_input.txt test1_expected.txt
        diff test1_input.txt test1_expected.txt

    - name: Test with 1 number
      run: python find_lowest_number.py test2_input.txt test2_expected.txt
        diff test2_input.txt test2_expected.txt

    - name: Test with blank file
      run: python find_lowest_number.py test3_input.txt test3_expected.txt
        diff test3_input.txt test3_expected.txt
