name: Test App
on: [push]
jobs:
  test-app:
    name: Run Application Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
          python-version: "3.10"
    - name: Test with 10 numbers
      run: python find_lowest_number.py test_data/test1_input.txt test_data/lowest_num.txt
    - name: Compare expected output to actual lowest num
      run: diff test_data/lowest_num.txt test_data/test1_expected.txt 

    - name: Test with 1 number
      run: python find_lowest_number.py test_data/test2_input.txt test_data/number.txt
    - name: Compare expected output to number
      run: diff test_data/number.txt test_data/test2_expected.txt 

    - name: Test with blank file
      run: python find_lowest_number.py test_data/test3_input.txt test_data/blank.txt
    - name: Compare expected output to blank
      run: diff test_data/blank.txt test_data/test3_expected.txt
